[project]
name = "hammer-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "emgeniussdk>=0.0.2a4",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pyqt6>=6.10.1",
]
